name: fastaqm_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+9

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #ui
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  curved_navigation_bar: ^1.0.3
  font_awesome_flutter: ^10.6.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  flutter_qiblah: ^2.2.0
  # permission
  permission_handler: ^11.0.1
  #bloc
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  #quran
  quran: ^1.2.2
  # clean
  equatable: ^2.0.5
  dartz: ^0.10.1
  # dio
  #dio: ^5.3.2
  #service locator
  #get_it: ^7.6.4
  #cache
  shared_preferences: ^2.2.2
  #location
  geolocator: ^9.0.2
  geocoding: ^2.1.1
  #share
  share: ^2.0.4
  #rename
  rename: ^3.0.1
  # responsive
  flutter_screenutil: ^5.9.0
  #audioplayers
  audioplayers: ^5.2.0
  assets_audio_player: ^3.1.1
  #scroll to
  scrollable_positioned_list: ^0.3.8
  #pray_time
  adhan: ^2.0.0+1
  #date_hijry
  hijri: ^3.0.0
  #animation
  animated_button: ^0.2.0
  scroll_snap_list: ^0.9.1
  #notification
  onesignal_flutter: ^5.0.3
  flutter_local_notifications: ^15.1.2
  flutter_timezone: ^1.0.8
  #firebase
  firebase_core: ^2.21.0
  #firebase_messaging: ^14.7.3
  #check internet
  internet_connection_checker: ^1.0.0+1
  #dio
  dio: ^5.3.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/audios/


  fonts:
    - family: quran
      fonts:
        - asset: assets/fonts/HafsSmart_08.ttf
    - family: me_quran
      fonts:
        - asset: assets/fonts/me_quran.ttf
