// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa18iQ-w-0HZPBlA1yhhitX_Kp0aVO1W4',
    appId: '1:852041153282:web:137bb4373d570941d3e01b',
    messagingSenderId: '852041153282',
    projectId: 'fastakm',
    authDomain: 'fastakm.firebaseapp.com',
    storageBucket: 'fastakm.appspot.com',
    measurementId: 'G-26HZMNQQF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeR_4Ul01RqxshTS3eNKhKk6Y682lsP8c',
    appId: '1:852041153282:android:d3743740672e8bc6d3e01b',
    messagingSenderId: '852041153282',
    projectId: 'fastakm',
    storageBucket: 'fastakm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxunsP4YMSDYayXtsqnh5EmbqwlIJq154',
    appId: '1:852041153282:ios:8ecacf6e3d9d8f6ad3e01b',
    messagingSenderId: '852041153282',
    projectId: 'fastakm',
    storageBucket: 'fastakm.appspot.com',
    iosBundleId: 'com.example.fastaqmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxunsP4YMSDYayXtsqnh5EmbqwlIJq154',
    appId: '1:852041153282:ios:22acc1f8817dcab9d3e01b',
    messagingSenderId: '852041153282',
    projectId: 'fastakm',
    storageBucket: 'fastakm.appspot.com',
    iosBundleId: 'com.example.fastaqmApp.RunnerTests',
  );
}
